from snakemake.utils import min_version

min_version("6.5")


report: "report/workflow.rst"


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trimming.smk"
include: "rules/mapping.smk"
include: "rules/qc.smk"


rule all:
    input:
        get_collect_bams_input,
        "results/qc/multiqc.html",
